apiVersion: apps/v1
kind: Deployment
metadata:
  name: sampleapp
  labels:
    app: sampleapp
spec:
  selector:
    matchLabels:
      app: sampleapp
  replicas: 6
  template:
    metadata:
      labels:
        app: sampleapp
        akka-cluster: sample
        env: Development
      annotations:
        akka.remote.dot-netty.tcp.port: "2551"
    spec:
      containers:
      - name: sampleapp
        image: localhost:5000/sampleapp:20
        ports:
        - containerPort: 2551
        resources:
          limits:
            memory: 256Mi
            cpu: "250m"
          requests:
            memory: 128Mi
            cpu: "80m"